name: Laravel + React CI - Test Only

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Combined Backend and Frontend Test job
  combined:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'

      - name: Install Composer dependencies
        run: |
          curl -sS https://getcomposer.org/installer | php
          php composer.phar install --no-interaction --prefer-dist

      - name: Install Frontend dependencies
        run: |
          npm install --no-dev # Install frontend dependencies

      - name: Build React project
        run: |
          npm run build --no-dev  # Build React app
